# Generated by Django 4.1.2 on 2022-11-24 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombreProducto', models.TextField(primary_key=True, serialize=False)),
                ('modelo', models.TextField()),
                ('unidadesProducto', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('detalles', models.TextField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('importe', models.IntegerField()),
                ('unidadesCompra', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
            ],
        ),
    ]
